{{- if eq .Values.namespace.type "solution" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: solution-builder
  labels:
    {{- include "aurora-namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: solution-builder
{{- if .Values.rbac.groups }}
subjects:
{{- range .Values.rbac.groups }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ . }}"
{{- end }}
{{- else }}
subjects: []
{{- end }}
{{- end }}
