{{- if eq .Values.namespace.type "solution" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/description: Service account provided for deployment of applications.
  labels:
    {{- include "aurora-namespace.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "deployment-%s" .Release.Name }}
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/description: Provides the deployment service account with the same access as solution builders.
  labels:
    {{- include "aurora-namespace.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: deployment
    namespace: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: solution-builder
---
apiVersion: v1
kind: Secret
metadata:
  name: deployment-token
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/description: The long-lived token for the deployment service account.
    kubernetes.io/service-account.name: deployment
  labels:
    {{- include "aurora-namespace.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
