{{- if (or (gt (len .Values.rbac.platformAdmin.groups) 0) (gt (len .Values.rbac.platformAdmin.users) 0)) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-rbac-cluster-admin"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: rbac-platform-admin
      values: |
        resources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: cluster-operator-admin
              annotations:
                kubernetes.io/description: |-
                  Binding to the cluster-admin role which gives cluster-wide
                  administrative access.
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cluster-admin
              subjects:
                {{- range .Values.rbac.platformAdmin.groups }}
                - apiGroup: rbac.authorization.k8s.io
                  kind: Group
                  name: {{ . }}
                {{- end }}
                {{- range .Values.rbac.platformAdmin.users }}
                - apiGroup: rbac.authorization.k8s.io
                  kind: User
                  name: {{ . }}
                {{- end }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
