apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-rbac-platform-operator-view"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: rbac-platform-operator-view
      values: |
        resources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: platform-operator-view
              annotations:
                kubernetes.io/description: |-
                  The permissions that platform-operators need for seeing the state of the platform.
                  This is an aggregated role and should not be modified directly.
              labels:
                app.kubernetes.io/name: "rbac-platform-operator-view"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: platform-operator-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            aggregationRule:
              clusterRoleSelectors:
              - matchLabels:
                  rbac.ssc-spc.gc.ca/aggregate-to-platform-operator-view: "true"
            rules: [] # The control plane automatically fills in the rules

          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: platform-operator-view-k8s
              annotations:
                kubernetes.io/description: |-
                  The permissions relating that platform-operators need for daily activities.
              labels:
                rbac.ssc-spc.gc.ca/aggregate-to-platform-operator-view: "true"
                app.kubernetes.io/name: "rbac-platform-operator-view"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: platform-operator-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            rules:
              # Read all core resources except secrets
              - apiGroups:
                  - ""
                resources:
                  - componentstatuses
                  - configmaps
                  - endpoints
                  - events
                  - limitranges
                  - namespaces
                  - nodes
                  - persistentvolumeclaims
                  - persistentvolumes
                  - pods
                  - podtemplates
                  - replicationcontrollers
                  - resourcequotas
                  - serviceaccounts
                  - services
                verbs:
                  - get
                  - list
                  - watch

              # Read access to all other resources
              - apiGroups:
                  - admissionregistration.k8s.io
                  - apiextensions.k8s.io
                  - apiregistration.k8s.io
                  - apps
                  - authentication.k8s.io
                  - authorization.k8s.io
                  - autoscaling
                  - batch
                  - certificates.k8s.io
                  - coordination.k8s.io
                  - discovery.k8s.io
                  - events.k8s.io
                  - flowcontrol.apiserver.k8s.io
                  - metrics.k8s.io
                  - networking.k8s.io
                  - node.k8s.io
                  - policy
                  - rbac.authorization.k8s.io
                  - scheduling.k8s.io
                  - snapshot.storage.k8s.io
                  - storage.k8s.io
                resources:
                  - "*"
                verbs:
                  - get
                  - list
                  - watch

          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: platform-operator-daily
              annotations:
                kubernetes.io/description: |-
                  The permissions that platform-operators need for daily activities.
                  This is an aggregated role and should not be modified directly.
              labels:
                app.kubernetes.io/name: "rbac-platform-operator-view"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: platform-operator-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: platform-operator-daily
            {{- if (or .Values.rbac.platformOperator.groups .Values.rbac.platformOperator.users) }}
            subjects:
              {{- range .Values.rbac.platformOperator.groups }}
              - apiGroup: rbac.authorization.k8s.io
                kind: Group
                name: {{ . }}
              {{- end }}
              {{- range .Values.rbac.platformOperator.users }}
              - apiGroup: rbac.authorization.k8s.io
                kind: User
                name: {{ . }}
              {{- end }}
            {{- else }}
            subjects: []
            {{- end }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
