apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-rbac-platform-operator-maintenance"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: rbac-platform-operator-maintenance
      values: |
        resources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: platform-operator-maintenance
              annotations:
                kubernetes.io/description: |-
                  The permissions that platform-operators need for daily activities in platform namespaces.
                  This is an aggregated role and should not be modified directly.
              labels:
                app.kubernetes.io/name: "rbac-platform-operator-maintenance"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: platform-operator-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            aggregationRule:
              clusterRoleSelectors:
              - matchLabels:
                  rbac.ssc-spc.gc.ca/aggregate-to-platform-operator-maintenance: "true"
            rules: [] # The control plane automatically fills in the rules

          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: platform-operator-namespace-maintenance
              annotations:
                kubernetes.io/description: |-
                  The permissions that platform-operators need for daily tasks on
                  namespaced resources such as scaling or restarting scalesets,
                  access to pod logs.
                  Note: This role should only be bound using a RoleBinding
                  in system namespaces.
              labels:
                rbac.ssc-spc.gc.ca/aggregate-to-platform-operator-maintenance: "true"
                app.kubernetes.io/name: "rbac-platform-operator-maintenance"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: platform-operator-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            rules:
              # Access pod logs
              - apiGroups:
                  - ""
                resources:
                  - pods/log
                verbs:
                  - get
              # View secrets
              - apiGroups:
                  - ""
                resources:
                  - secrets
                verbs:
                  - get
                  - list
                  - watch
              # Scale and restart deployments and statefuls
              - apiGroups:
                  - apps
                resources:
                  - deployments
                  - deployments/scale
                  - statefulsets
                  - statefulsets/scale
                verbs:
                  - get
                  - list
                  - patch
                  - watch
              # Create one-offs of CronJobs
              - apiGroups:
                  - batch
                resources:
                  - cronjobs
                verbs:
                  - get
                  - list
                  - watch
              - apiGroups:
                  - batch
                resources:
                  - jobs
                verbs:
                  - create
                  - get
                  - list
                  - watch
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
