apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-rbac-solution-builder"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: rbac-solution-builder
      values: |
        resources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: solution-builder
              labels:
                app.kubernetes.io/name: "rbac-solution-builder"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: solution-builder-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            aggregationRule:
              clusterRoleSelectors:
              - matchLabels:
                  rbac.ssc-spc.gc.ca/aggregate-to-solution-builder: "true"
            rules: [] # The control plane automatically fills in the rules
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: solution-builder-core
              labels:
                rbac.ssc-spc.gc.ca/aggregate-to-solution-builder: "true"
                app.kubernetes.io/name: "rbac-solution-builder"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: solution-builder-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            rules:
              - apiGroups:
                  - ""
                resources:
                  - resourcequotas
                  - endpoints
                  - events
                verbs: [list, get, watch]
              - apiGroups:
                  - ""
                resources:
                  - configmaps
                  - persistentvolumeclaims
                  - pods
                  - pods/attach
                  - pods/exec
                  - pods/log
                  - pods/portforward
                  - replicationcontrollers
                  - secrets
                  - serviceaccounts
                  - services
                  - services/proxy
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - apps
                resources:
                  - deployments
                  - deployments/scale
                  - replicasets
                  - replicasets/scale
                  - statefulsets
                  - statefulsets/scale
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - autoscaling
                resources:
                  - horizontalpodautoscalers
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - policy
                resources:
                  - poddisruptionbudgets
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - batch
                resources:
                  - cronjobs
                  - jobs
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - rbac.authorization.k8s.io
                resources:
                  - roles
                  - rolebindings
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - metrics.k8s.io
                resources:
                  - pods
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - networking.k8s.io
                resources:
                  - ingresses
                  - networkpolicies
                verbs: [get, list, watch, create, update, patch, delete]
              - apiGroups:
                  - sparkoperator.k8s.io
                resources:
                  - sparkapplications
                verbs: [get, list, watch, create, update, patch, delete]

  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
