{{ if .Values.components.gatekeeper.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-gatekeeper-templates"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: {{ default "https://github.com/gccloudone-aurora/gatekeeper-policies.git" .Values.components.gatekeeper.templates.repository }}
    path: {{ default "." .Values.components.gatekeeper.templates.path }}
    targetRevision: {{ default "main" .Values.components.gatekeeper.templates.targetRevision }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
