{{ if .Values.components.istio.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-istio-base"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ default "base" .Values.components.istio.base.helm.chart }}
    {{- if .Values.components.istio.base.helm.repository }}
    repoURL: {{ .Values.components.istio.base.helm.repository }}
    {{- else }}
    repoURL: {{ default "https://istio-release.storage.googleapis.com/charts" .Values.global.helm.repository }}
    {{- end }}
    targetRevision: {{ default "1.16.1" .Values.components.istio.base.helm.targetRevision }}
    helm:
      releaseName: istio-base
  destination:
    name: '{{ .Values.global.cluster }}'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  # The webhook's failurePolicy changes from Ignore to Fail
  # afer the deployment has completed.
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jsonPointers:
    - /webhooks/0/failurePolicy

{{- end }}
