{{ if .Values.components.istio.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-istio-rbac"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: istio-rbac
      values: |
        resources:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: solution-builder-istio
              labels:
                rbac.ssc-spc.gc.ca/aggregate-to-solution-builder: "true"
                app.kubernetes.io/name: "istio-rbac"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: solution-builder-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            rules:
              - apiGroups:
                  - networking.istio.io
                resources:
                  - destinationrules
                  - serviceentries
                  - sidecars
                  - virtualservices
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - patch
                  - delete
              - apiGroups:
                  - security.istio.io
                resources:
                  - authorizationpolicies
                  - peerauthentications
                  - requestauthentications
                verbs:
                  - get
                  - list
                  - watch
                  - create
                  - update
                  - patch
                  - delete
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: istio-view-all
              annotations:
                kubernetes.io/description: "Allows viewing of all istio CRDs."
              labels:
                rbac.ssc-spc.gc.ca/aggregate-to-platform-operator-view: "true"
                app.kubernetes.io/name: "istio-rbac"
                app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                app.kubernetes.io/part-of: platform-operator-rbac
                app.kubernetes.io/managed-by: argo
                helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
            rules:
              - apiGroups:
                  - extensions.istio.io
                  - install.istio.io
                  - networking.istio.io
                  - security.istio.io
                  - telemetry.istio.io
                resources:
                  - '*'
                verbs:
                  - get
                  - list
                  - watch
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
