{{ if .Values.components.kiali.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-kiali-netpol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: kiali-netpol
      values: |
        resources:
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-namespace
              namespace: kiali-system
            spec:
              podSelector: {}
              policyTypes:
                - Ingress
                - Egress
              ingress:
                - from:
                  - podSelector: {}
              egress:
                - to:
                  - podSelector: {}
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-ingress-from-prometheus-to-kiali
              namespace: kiali-system
            spec:
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      namespace.ssc-spc.gc.ca/purpose: system
                      kubernetes.io/metadata.name: prometheus-system
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: prometheus
                      app.kubernetes.io/instance: kube-prometheus-stack-prometheus
              podSelector:
                matchLabels:
                  app.kubernetes.io/part-of: kiali
              policyTypes:
              - Ingress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-ingress-from-grafana-to-kiali
              namespace: kiali-system
            spec:
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      namespace.ssc-spc.gc.ca/purpose: system
                      kubernetes.io/metadata.name: prometheus-system
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: grafana
              podSelector:
                matchLabels:
                  app.kubernetes.io/part-of: kiali
              policyTypes:
              - Ingress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-prometheus-from-kiali
              namespace: kiali-system
            spec:
              egress:
                - to:
                  - namespaceSelector:
                      matchLabels:
                        namespace.ssc-spc.gc.ca/purpose: system
                        kubernetes.io/metadata.name: prometheus-system
                    podSelector:
                      matchLabels:
                        app.kubernetes.io/name: prometheus
                        app.kubernetes.io/instance: kube-prometheus-stack-prometheus
              podSelector:
                matchLabels:
                  app.kubernetes.io/part-of: kiali
              policyTypes:
              - Egress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-grafana-from-kiali
              namespace: kiali-system
            spec:
              egress:
                - to:
                  - namespaceSelector:
                      matchLabels:
                        namespace.ssc-spc.gc.ca/purpose: system
                        kubernetes.io/metadata.name: prometheus-system
                    podSelector:
                      matchLabels:
                        app.kubernetes.io/name: grafana
              podSelector:
                matchLabels:
                  app.kubernetes.io/part-of: kiali
              policyTypes:
              - Egress
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
