apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-gatekeeper-restrict-pod-labels"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    kubernetes.io/description: |
      Ensures that solution builders cannot assign certain pod labels
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: gatekeeper-restrict-pod-labels
      values: |
        resources:
          - apiVersion: constraints.gatekeeper.sh/v1beta1
            kind: RestrictPodLabels
            metadata:
              name: restrict-pod-labels
            spec:
              match:
                namespaceSelector:
                  matchExpressions:
                    - key: namespace.ssc-spc.gc.ca/purpose
                      operator: In
                      values:
                        - solution
                kinds:
                  - apiGroups: [""]
                    kinds: ["Pod"]
                excludedNamespaces: {{ toYaml .Values.components.gatekeeper.constraints.restrictPodLabels.excludedNamespaces | nindent 18 }}
              enforcementAction: {{ .Values.components.gatekeeper.constraints.restrictPodLabels.enforcementAction }}
              parameters:
                labels: {{ .Values.components.gatekeeper.constraints.restrictPodLabels.restrictedLabels | toYaml | nindent 18 }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
