{{ if .Values.components.velero.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-velero-netpol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: velero-netpol
      values: |
        resources:
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-namespace
              namespace: velero-system
            spec:
              podSelector: {}
              policyTypes:
                - Ingress
                - Egress
              ingress:
                - from:
                  - podSelector: {}
              egress:
                - to:
                  - podSelector: {}
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-azureapi-from-velero
              namespace: velero-system
            spec:
              egress:
              - ports:
                - port: 443
                  protocol: TCP
                to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: velero
              policyTypes:
              - Egress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-azureidentity-from-velero
              namespace: velero-system
            spec:
              egress:
              - ports:
                - port: 80
                  protocol: TCP
                to:
                - ipBlock:
                    cidr: 169.254.169.254/32
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: velero
              policyTypes:
              - Egress
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
