{{ if .Values.components.auroraController.enabled -}}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-aurora-controller-manifests"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "aurora-controller-manifests"
        - name: HELM_VALUES
          value: |
            resources:
              - apiVersion: v1
                kind: Secret
                metadata:
                  name: aurora-controller-image-pull-secret
                  namespace: aurora-controller-system
                  labels:
                    app.kubernetes.io/name: "aurora-controller-manifests"
                    app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                    app.kubernetes.io/component: config
                    app.kubernetes.io/part-of: aurora-controller-system
                    app.kubernetes.io/managed-by: argo
                    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
                type: kubernetes.io/dockerconfigjson
                data:
                  .dockerconfigjson: {{ required "auroraController.aurora.secretDockerConfigJson is required" .Values.components.auroraController.aurora.secretDockerConfigJson | b64enc }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

{{- end }}
