apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-cert-manager-alerts"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    plugin:
      env:
        - name: HELM_RELEASE_NAME
          value: "cert-manager-alerts"
        - name: HELM_VALUES
          value: |
            resources:
            - apiVersion: monitoring.coreos.com/v1
              kind: PrometheusRule
              metadata:
                name: cert-manager-alerts
                namespace: cert-manager-system
                labels:
                  app.kubernetes.io/name: "cert-manager-alerts"
                  app.kubernetes.io/instance: "{{ .Values.global.cluster }}"
                  app.kubernetes.io/component: monitoring
                  app.kubernetes.io/part-of: cert-manager-system
                  app.kubernetes.io/managed-by: argo
                  helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
                annotations:
                  rules-definition: >-
                    https://github.com/gccloudone-aurora-platform-charts/-/blob/main/charts/aurora-platform/charts/aurora-core/conf/prometheus_rules/cert_manager/cert_manager_rules.yaml
              spec: {{ (.Files.Get "conf/prometheus_rules/cert_manager/cert_manager_rules.yaml")  | nindent 16 }}
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
