apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.global.cluster }}-cert-manager-netpol"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    chart: {{ .Values.global.raw.helm.chart }}
    repoURL: {{ default .Values.global.helm.repository .Values.global.raw.helm.repository }}
    targetRevision: {{ .Values.global.raw.helm.targetRevision }}
    helm:
      releaseName: cert-manager-netpol
      values: |
        resources:
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-namespace
              namespace: cert-manager-system
            spec:
              podSelector: {}
              policyTypes:
                - Ingress
                - Egress
              ingress:
                - from:
                  - podSelector: {}
              egress:
                - to:
                  - podSelector: {}
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-letsencrypt-from-cert-manager
              namespace: cert-manager-system
            spec:
              egress:
              - ports:
                - port: 443
                  protocol: TCP
                to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: cert-manager
                  app.kubernetes.io/component: controller
              policyTypes:
              - Egress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-azuredns-from-cert-manager
              namespace: cert-manager-system
            spec:
              egress:
              - ports:
                - port: 443
                  protocol: TCP
                to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: cert-manager
                  app.kubernetes.io/component: controller
              policyTypes:
              - Egress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-publicdns-from-cert-manager
              namespace: cert-manager-system
            spec:
              egress:
              - ports:
                - port: 53
                  protocol: TCP
                to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: cert-manager
                  app.kubernetes.io/component: controller
              policyTypes:
              - Egress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-egress-to-azureidentity-from-cert-manager
              namespace: cert-manager-system
            spec:
              egress:
              - ports:
                - port: 80
                  protocol: TCP
                to:
                - ipBlock:
                    cidr: 169.254.169.254/32
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: cert-manager
                  app.kubernetes.io/component: controller
              policyTypes:
              - Egress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-ingress-from-apiserver-to-certmanagerwebhook
              namespace: cert-manager-system
            spec:
              ingress:
              - from:
                - ipBlock:
                    cidr: {{ required "global.apiServerCidr is required" .Values.global.apiServerCidr | quote }}
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      app: konnectivity-agent
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: webhook
                  app.kubernetes.io/component: webhook
              policyTypes:
              - Ingress
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-ingress-from-prometheus-to-certmanager
              namespace: cert-manager-system
            spec:
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      namespace.ssc-spc.gc.ca/purpose: system
                      kubernetes.io/metadata.name: prometheus-system
                  podSelector:
                    matchLabels:
                      app.kubernetes.io/name: prometheus
                      app.kubernetes.io/instance: kube-prometheus-stack-prometheus
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: cert-manager
                  app.kubernetes.io/instance: cert-manager
              policyTypes:
              - Ingress
  destination:
    name: {{ .Values.global.cluster }}
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
