{{- if .Values.argocdInstance.ingressDomain }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  labels:
    use-azuredns-solver: "true"
    {{- include "argocd-foundation.labels" $ | nindent 4 }}
spec:
  commonName: {{ .Values.argocdInstance.ingressDomain }}
  dnsNames:
    - {{ .Values.argocdInstance.ingressDomain }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: argocd-server-tls
{{- end }}
