 groups:
  - name: nodepool-status.rules
    rules:
      - expr: 'sum by (cluster, label_agentpool, thanos_ruler_replica) (kube_node_status_allocatable{resource="pods", job="kube-state-metrics"} * on (node) group_left(label_agentpool) kube_node_labels{job="kube-state-metrics"})'
        record: nodepool_allocatable_pods
      - expr: 'sum by (cluster, total_nodepool, thanos_ruler_replica) (label_replace(nodepool_allocatable_pods, "total_nodepool", "$$1", "label_agentpool", "(.*)[0-9].*"))'
        record: total_nodepool_allocatable_pods
      - expr: 'sum by (cluster, label_agentpool, thanos_ruler_replica) (node_unterminated_pods_total * on (cluster, node) group_left(label_agentpool) kube_node_labels{job="kube-state-metrics"})'
        record: nodepool_allocated_pods
      - expr: 'sum by (cluster, total_nodepool, thanos_ruler_replica) (label_replace(nodepool_allocated_pods, "total_nodepool", "$$1", "label_agentpool", "(.*)[0-9].*"))'
        record: total_nodepool_allocated_pods

      - alert: TotalNodepoolPodsFull
        annotations:
          message: '{{ if eq $$labels.total_nodepool ""}}Control plane or unpooled node"{{ else }}Total nodepool {{ $$labels.total_nodepool }}{{end}} pod count is {{ printf "%.2f" $$value }}% of capacity!'
          runbook: "https://aurora.gccloudone.ca/en/documentation/monitoring-surveillance/prometheus/cluster-alert-runbooks/node-pool-pod-capacity/#alert-nodepoolpodsfull"
        expr: "total_nodepool_allocated_pods/total_nodepool_allocatable_pods * 100 > 95"
        for: 2m
        labels:
          scope: cluster
          severity: P1-Critical

      - alert: TotalNodepoolReachingPodCapacity
        annotations:
          message: '{{ if eq $$labels.total_nodepool ""}}Control plane or unpooled node"{{ else }}Total nodepool {{ $$labels.total_nodepool }}{{end}} pod count is {{ printf "%.2f" $$value }}% of capacity.'
          runbook: "https://aurora.gccloudone.ca/en/documentation/monitoring-surveillance/prometheus/cluster-alert-runbooks/node-pool-pod-capacity/#alert-nodepoolreachingpodcapacity"
        expr: 'total_nodepool_allocated_pods/total_nodepool_allocatable_pods * 100 > 85'
        for: 10m
        labels:
          scope: cluster
          severity: P3-Minor

      - alert: NodepoolPodsFull
        annotations:
          message: '{{ if eq $$labels.label_agentpool ""}}Control plane or unpooled node"{{ else }}Nodepool {{ $$labels.label_agentpool }}{{end}} pod count is {{ printf "%.2f" $$value }}% of capacity.'
          runbook: "https://aurora.gccloudone.ca/en/documentation/monitoring-surveillance/prometheus/cluster-alert-runbooks/node-pool-pod-capacity/#alert-nodepoolpodsfull"
        expr: "nodepool_allocated_pods/nodepool_allocatable_pods * 100 > 95"
        for: 2m
        labels:
          scope: cluster
          severity: P4-Warning
